export const questions: string[] = [
  'Para mi es importante recibir la aprobación de los demás.',
  'Odio equivocarme en algo.',
  'La gente que se equivoca, logra lo que se merece.',
  'Generalmente acepto los acontecimientos con filosofía.',
  'Si una persona quiere, puede ser feliz en casi cualquier circunstancia.',
  'Temo a las cosas que, a menudo, me resultan objeto de preocupación.',
  'Normalmente aplazo las decisiones importantes.',
  'Todo el mundo necesita de alguien a quién recurrir en busca de ayuda y consejo.',
  '"Una cebra no puede cambiar sus rayas".',
  'Prefiero sobre todas las cosas pasar el tiempo libre de una forma tranquila.',
  'Me gusta que los demás me respeten, pero yo no tengo porque respetar a nadie.',
  'Evito las cosas que no puedo hacer bien.',
  'Hay demasiadas personas malas que escapan del castigo del infierno.',
  'Las frustraciones no me distorsionan.',
  'A la gente no le trastornan los acontecimientos sino la imagen que tiene de ellos.',
  'Me producen poca ansiedad los peligros inesperados o los acontecimientos futuros.',
  'Trato de afrontar los trabajos fastidiosos y hacerlos cuanto antes.',
  'En las decisiones importantes, consulto con una autoridad al respecto.',
  'Es casi imposible superar la influencia del pasado.',
  'Me gusta disponer de muchos recursos.',
  'Quiero gustar a todo el mundo.',
  'No me gusta competir en actividades en las que los demás son mejores que yo.',
  'Aquellos que se equivocan merecen cargar con la culpa.',
  'Las cosas deberían ser distintas a como son.',
  'Yo provoco mi propio mal humor.',
  'A menudo, no puedo quitarme algún asunto de la cabeza.',
  'Evito enfrentarme a los problemas.',
  'Todo el mundo necesita tener fuera de si mismo una fuente de energía.',
  'Solo porque una vez algo afecto tu vida de forma importante, no quiere decir que tenga que ser igual en el futuro.',
  'Me siento mas satisfecho cuando tengo muchas cosas que hacer.',
  'Puedo gustarme a mi mismo aun cuando no guste a los demás.',
  'Me gustaría triunfar en algo, pero no pienso que deba hacerlo.',
  'La inmoralidad debería castigarse severamente.',
  'A menudo me siento trastornado por situaciones que no me gustan.',
  'Las personas desgraciadas, normalmente, se deben este estado a si mismas.',
  'No me preocupo por no poder evitar que algo ocurra.',
  'Normalmente tomo las decisiones tan pronto como puedo.',
  'Hay determinadas personas de las que dependo mucho.',
  'La gente sobre-valora la influencia del pasado.',
  'Lo que mas me divierte es realizar algún proyecto creativo.',
  'Si no gusto a los demás es su problema, no el mio.',
  'Para mi es muy importante alcanzar el éxito en todo lo que hago.',
  'Yo pocas veces culpo a la gente de sus errores.',
  'Normalmente acepto las cosas como son aunque no me gusten.',
  'Nadie esta mucho tiempo enfadado, a menos que quiera estarlo.',
  'No puedo soportar correr riesgos.',
  'La vida es demasiado corta para pasarla haciendo cosas que a uno no le gustan.',
  'Me gusta valerme por mi mismo.',
  'Si hubiera vivido experiencias distintas, podría ser mas como me gustaría ser.',
  'Me gustaría jubilarme y apartarme totalmente del trabajo.',
  'Pienso que es duro ir en contra de lo que piensan los demás.',
  'Disfruto de las actividades independientemente de lo bueno/malo que sea en ellas.',
  'El miedo al castigo es lo que hace a la gente ser buena.',
  'Si las cosas me desagradan, opto por ignorarlas.',
  'Cuanto mas problemas tiene una persona, menos feliz es.',
  'Raramente me siento ansioso al pensar en el futuro.',
  'Raramente aplazo las cosas.',
  'Yo soy el único que realmente puede entender y solucionar mis problemas.',
  'Normalmente no pienso que las experiencias pasadas me afecten en la actualidad.',
  'Tener demasiado tiempo libre resulta aburrido.',
  'Me gusta recibir la aprobación de los demás, pero no tengo necesidad real de ello.',
  'Me fastidia que los demás sean mejores que yo en algo.',
  'Todo el mundo es, esencialmente, bueno.',
  'Hago todo lo que puedo por conseguir lo que quiero y una vez conseguido, deja de preocuparme.',
  'Nada es intrínsecamente perturbador, si lo es, se debe al modo en que lo interpretamos.',
  'Me preocupan mucho determinadas cosas del futuro.',
  'Me resulta difícil hacer las tareas desagradable.',
  'Me desagrada que los demás tomen decisiones por mi.',
  'Somos esclavos de nuestro pasado.',
  'A veces desearía poder irme a una isla tropical, y tenderme en la playa sin hacer nada más.',
  'A menudo me preocupa que la gente me apruebe y me acepte.',
  'Me trastorna cometer errores.',
  'No es equitativo que "llueva igual sobre el justo que sobre el injusto".',
  'Yo disfruto honradamente de la vida.',
  'Debería haber mas personas que afrontaran lo desagradable de la vida.',
  'Algunas veces me resulta imposible apartar de mi mente el miedo a algo.',
  'Una vida fácil, muy pocas veces resulta compensadora.',
  'Pienso que es fácil buscar ayuda.',
  'Una vez que algo afecta a tu vida de forma importante, seguirá haciéndolo siempre.',
  'Me encanta estar tumbado.',
  'Tengo considerable preocupación por lo que la gente piensa de mi.',
  'Muchas veces me enfado muchísimo por cosas sin importancia.',
  'Generalmente doy una segunda oportunidad a quién se equivoca.',
  'La gente es mas feliz cuando tiene metas y problemas que resolver.',
  'Nunca hay razón para permanecer afligido mucho tiempo.',
  'Raramente pienso en cosas como la muerte o la guerra nuclear.',
  'No me gustan las responsabilidades.',
  'No me gusta depender de los demás.',
  'La gente nunca cambia básicamente.',
  'La mayoría de las personas trabajan demasiado y no descansan lo suficiente.',
  'Ser criticado es algo fastidioso pero no perturbador.',
  'No me gusta hacer aquellas cosas que no hago del todo bien.',
  'Nadie es malo a pesar de que sus actos los sean.',
  'Raramente me importunan Ios errores de los demás.',
  'El hombre construye su propio infierno interior.',
  'Muchas veces me sorprendo planeando lo que haría si me encontrara en determinadas situaciones de peligro.',
  'Si tengo que hacer algo lo hago a pesar de que no sea agradable.',
  'He aprendido a no estar pendiente de nada que no este relacionado con mi bienestar.',
  'No miro atrás con resentimiento.',
  'No me siento realmente contento hasta que no estoy relajado y sin hacer nada.',
];
